apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: depilaciones-debby
data:
  NODE_ENV: "production"
  PORT: "5000"
  CORS_ORIGIN: "http://frontend-service"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: depilaciones-debby
type: Opaque
stringData:
  MONGODB_URI: "mongodb://mongodb-service:27017/depilaciones-debby"
